# Generated by Django 2.0.2 on 2019-01-17 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('snippet', models.TextField()),
                ('log_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
